GET https://w1b3r5hhue.execute-api.eu-west-2.amazonaws.com/prod/movies
###



POST https://w1b3r5hhue.execute-api.eu-west-2.amazonaws.com/prod/movies
Content-Type: application/json
{
  "title": "Black Panther 2",
  "year": "2025"
}
###




PUT https://w1b3r5hhue.execute-api.eu-west-2.amazonaws.com/prod/movies?id=22e44f77-2fd5-45d5-9c3f-98419e683ba7
Content-Type: application/json
{
  "year": "2000000000000001"
}
###




DELETE  https://w1b3r5hhue.execute-api.eu-west-2.amazonaws.com/prod/movies?id=22e44f77-2fd5-45d5-9c3f-98419e683ba7
###